; Configuration PHP pour l'environnement de développement Docker

[PHP]
display_errors = On
display_startup_errors = On
error_reporting = E_ALL
log_errors = On

memory_limit = 256M
max_execution_time = 60
upload_max_filesize = 32M
post_max_size = 32M

date.timezone = Europe/Paris

[opcache]
opcache.enable = 1
opcache.enable_cli = 1
opcache.memory_consumption = 128
opcache.interned_strings_buffer = 8
opcache.max_accelerated_files = 20000
opcache.revalidate_freq = 0
opcache.validate_timestamps = 1
