webpack_encore:
    output_path: '%kernel.project_dir%/public/build'
    strict_mode: false
    cache: false

    script_attributes:
        defer: true
    link_attributes: {}

when@prod:
    webpack_encore:
        cache: true
